version: "3"
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    environment:
      - FLASK_ENV=development

  frontend:
    build:
      context: .
      dockerfile: email-sender-ui/Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./email-sender-ui:/app
      - /app/node_modules
